# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  default_client: sample001
  secret_key_base: 67872c3c5691ce5d7270e9adb873c558f3f1f8899705785474c222a457ab86e30c24f4f7799596fe74834872c9f91d891cc631efb3d0e0be2f3edebe40d5b106
  

test:
  domain_name: example.com 
  secret_key_base: aeea79290fb8ae3c5cb22c014fe48a84e392683894b852aea6f659af06c7f036d02629fbae1e7b458b7340aba6ef87ed1b05f4997934e7fcd07f082a63e71b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  default_client: <%= ENV["DEFAULT_CLIENT"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
